version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    build: html  # default RTD HTML build

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
  system_packages: true

sphinx:
  configuration: docs/source/conf.py
