version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install nox
    build:
      - nox -s docs

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
  system_packages: true

sphinx:
  configuration: docs/source/conf.py
