version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    build:
      html:
        - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
