version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: poetry
      path: .   # <--- This is the critical missing piece
      extras: ["docs"]

sphinx:
  configuration: docs/source/conf.py
