# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
    - method: poetry
      with-project: true

  # override the install command to use poetry groups properly
  install-command: |
    poetry install --no-root --with docs

sphinx:
  configuration: docs/source/conf.py
