name: Lint and Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run Ruff
        run: |
          poetry run ruff check agent_logic/ docs/ tests/

      - name: Run Black (check only)
        run: |
          poetry run black --check agent_logic/ docs/ tests/
